# Generated by Django 4.2.1 on 2023-05-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_producto", models.CharField(max_length=100)),
                ("cantidad_bodega", models.IntegerField()),
                (
                    "cantidad_utilizada",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "costo_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("fecha_creacion", models.DateField(auto_now_add=True)),
                ("ultima_actualizacion", models.DateField(auto_now=True)),
            ],
        ),
    ]
